// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accountGroup': string;
  'closeButton': string;
  'closeButtonGroup': string;
  'closeButtonIcon': string;
  'logo': string;
  'profilePicker': string;
  'toolBar': string;
}
export const cssExports: CssExports;
export default cssExports;
