// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttons': string;
  'deleteButton': string;
  'field': string;
  'header': string;
  'modal': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
