// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'panel': string;
  'title': string;
  'titleBar': string;
}
export const cssExports: CssExports;
export default cssExports;
