// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backButtonIcon': string;
  'screen': string;
}
export const cssExports: CssExports;
export default cssExports;
