// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closeButton': string;
  'dismissToastIcon': string;
  'list': string;
  'notificationIcon': string;
  'pullOutTab': string;
  'title': string;
  'toast': string;
  'toastActions': string;
  'toastCountdown': string;
  'toastIcon': string;
  'toastInfo': string;
  'toastMessage': string;
  'toaster': string;
  'toasterHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
