// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'content': string;
  'fileName': string;
  'item': string;
  'profilePicture': string;
  'to': string;
}
export const cssExports: CssExports;
export default cssExports;
