// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttons': string;
  'changeFileButton': string;
  'clearFileButton': string;
  'clearFileButtonIcon': string;
  'errorMessage': string;
  'field': string;
  'fieldLabel': string;
  'modal': string;
  'selectFileButton': string;
  'selectedFileButtonGroup': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
