// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'changeFileButton': string;
  'clearFileButton': string;
  'clearFileButtonIcon': string;
  'errorMessage': string;
  'fieldLabel': string;
  'modal': string;
  'primaryButton': string;
  'secondaryButton': string;
  'selectedFileButtonGroup': string;
  'textField': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
