// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon-spin': string;
  'loadingIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
