// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'banner': string;
  'body': string;
  'closeButton': string;
  'closeButtonGroup': string;
  'closeButtonIcon': string;
  'errorMessage': string;
  'footer': string;
  'frame': string;
  'link': string;
  'logo': string;
  'prompt': string;
  'signInMethod': string;
  'signInMethods': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
