// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'primaryButton': string;
  'secondaryButton': string;
  'sendShareButton': string;
  'sideBar': string;
  'textField': string;
}
export const cssExports: CssExports;
export default cssExports;
