// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accountGroup': string;
  'arrow': string;
  'displayName': string;
  'dropdown': string;
  'dropdownItem': string;
  'picker': string;
  'pickerContent': string;
  'welcomeGroup': string;
  'welcomeText': string;
}
export const cssExports: CssExports;
export default cssExports;
