// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'deleteButton': string;
  'fileURL': string;
  'footer': string;
  'fromGroup': string;
  'fromProfile': string;
  'fromUser': string;
  'header': string;
  'item': string;
  'noText': string;
  'preview': string;
  'previewImage': string;
  'primaryButton': string;
  'secondaryButton': string;
  'textField': string;
}
export const cssExports: CssExports;
export default cssExports;
