// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'copyTextButton': string;
  'deleteButton': string;
  'footer': string;
  'fromGroup': string;
  'fromProfile': string;
  'fromUser': string;
  'header': string;
  'item': string;
  'preview': string;
  'viewButton': string;
}
export const cssExports: CssExports;
export default cssExports;
