// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backButtonIcon': string;
  'errorMessage': string;
  'itemGroup': string;
  'items': string;
  'label': string;
  'panelBody': string;
  'primaryButton': string;
  'screen': string;
  'secondaryButton': string;
  'textField': string;
}
export const cssExports: CssExports;
export default cssExports;
