// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'errorMessage': string;
  'inputs': string;
  'modal': string;
  'pfp': string;
  'pfpIcon': string;
  'primaryButton': string;
  'removePFPIcon': string;
  'secondaryButton': string;
  'textField': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
