// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'leftArrow': string;
  'picker': string;
  'profileLabel': string;
  'profileList': string;
  'rightArrow': string;
}
export const cssExports: CssExports;
export default cssExports;
