// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'defaultStar': string;
  'deleteProfileButton': string;
  'deleteProfileButtonContainer': string;
  'deleteProfileButtonIcon': string;
  'leftArrow': string;
  'picker': string;
  'profileImage': string;
  'profileLabel': string;
  'profileList': string;
  'rightArrow': string;
}
export const cssExports: CssExports;
export default cssExports;
