// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deleteProfileButton': string;
  'deleteProfileButtonContainer': string;
  'deleteProfileButtonIcon': string;
  'dragPreview': string;
  'leftArrow': string;
  'picker': string;
  'profileImage': string;
  'profileLabel': string;
  'profileList': string;
  'pulse-white': string;
  'rightArrow': string;
}
export const cssExports: CssExports;
export default cssExports;
