// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clearLink': string;
  'outboxItemList': string;
}
export const cssExports: CssExports;
export default cssExports;
